<?php

use Drupal\Core\Database\Database;

/**
 * Implements hook_uninstall().
 *
 * Cleans up config entities installed by this module.
 */
function migrate_sql_d8_custom_uninstall() {
  \Drupal::database()->query("DELETE FROM {config} WHERE name LIKE '%migrate_plus.migration.node_migrate_hi%'");
  \Drupal::database()->query("DELETE FROM {config} WHERE name LIKE '%migrate_plus.migration.node_migrate%'");
  drupal_flush_all_caches();
}
